product: 1.0.0
info:
  name: utility
  title: utility
  version: 1.0.0
visibility:
  view:
    enabled: true
    type: public
    tags: []
    orgs: []
  subscribe:
    enabled: true
    type: authenticated
    tags: []
    orgs: []
apis:
  utility:
    id: 586698c0e4b0f9e4b7f41851
plans:
  default:
    title: Default Plan
    description: Default Plan
    approval: false
    rate-limit:
      hard-limit: false
      value: 100/hour
